[package]
name = "jls-test"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
env_logger = "0.11.8"
hdrhistogram = { workspace = true }
quinn = { package = "quinn-jls", path = "../quinn-jls" }
quinn-proto = { package = "quinn-proto-jls", path = "../quinn-proto-jls" }
rcgen = { workspace = true }
rustls = { workspace = true, features = ["logging"]}
rustls-pemfile = { workspace = true }
serde = { workspace = true, optional = true  }
serde_json = { workspace = true, optional = true }
socket2 = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "signal", "net"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

rustls_raw = {workspace = true}
quinn_raw = {workspace = true}  # Still dependent on rustls-jls, don't know how to solve
